// vehicles
export const SET_VEHICLES = 'SET_VEHICLES';
export const SET_VEHICLE = 'SET_VEHICLE';
export const CLEAR_VEHICLES = 'CLEAR_VEHICLES';

// authentication
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

// policy hubs
export const SET_ACTIVE_PHASE = 'SET_ACTIVE_PHASE'
export const TOGGLE_VISIBLE_LAYER = 'TOGGLE_VISIBLE_LAYER'
export const UNSET_VISIBLE_LAYER = 'UNSET_VISIBLE_LAYER'
export const SET_VISIBLE_LAYER = 'SET_VISIBLE_LAYER'
export const SET_VISIBLE_LAYERS = 'SET_VISIBLE_LAYERS'
export const SET_SELECTED_POLICY_HUBS = 'SET_SELECTED_POLICY_HUBS'
export const SET_SHOW_COMMIT_FORM = 'SET_SHOW_COMMIT_FORM'
export const SET_HUBS_IN_DRAWING_MODE = 'SET_HUBS_IN_DRAWING_MODE'
export const SET_IS_DRAWING_ENABLED = 'SET_IS_DRAWING_ENABLED'
